name: Test CI

on:
  push:
    branches:
      - staging.*
  workflow_dispatch:
      
env:
  DOCKER_IMAGE_PORTAL: ritchie-portal
  
jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Echo env var
        run: echo $DOCKER_IMAGE_PORTAL
