name: Build

on:
  push:
    branches:
      - staging.*
  workflow_dispatch:
  
env:
  DOCKER_IMAGE_PORTAL: ritchie-portal
  RITCHIE_AWS_REGION: sa-east-1

jobs:
  set_env_vars:
    name: Setting environment variables
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Staging
        if: contains(github.ref, 'staging')
        run: export TEST=github.ref
      - name: Echo github.ref
        run: echo 'Não está no contexto staging'
        
  get_env_var:
    runs-on: ubuntu-latest
    needs: [set_env_vars]
    
    steps:
      - name: Get env var
        run: echo ${{ env.TEST }}
    
