name: Build

on:
  push:
    branches:
      - staging.*
  workflow_dispatch:
  
env:
  DOCKER_IMAGE_PORTAL: ritchie-portal
  RITCHIE_AWS_REGION: sa-east-1

jobs:
  set_env_vars:
    name: Setting environment variables
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Staging
        if: contains('refs/heads/staging', github.ref)
        run: echo ${{github.ref}}
      - name: Echo github.ref
        run: echo 'Não está no contexto staging'
    
